# Generated by Django 4.2.15 on 2024-09-16 11:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/image-placeholder.webp', force_format='WEBP', keep_meta=True, quality=100, scale=None, size=None, upload_to='profiles/'),
        ),
    ]
